# ansible target1 -m lineinfile -a path=/tmp/alain line="nameserver 8.8.8.8"
-
  name: add line to file
  hosts: target1
  tasks:
    - name: touch file
      file:
        state: touch
        path: /tmp/alain
    - name: add line to file
      lineinfile: 
        path: /tmp/alain
        line: nameserver 8.8.8.8
